### ISSUE TITLE
Ios 버전 지원

### ISSUE THREAD

**Issue by gomjellie** [fimuxd/GITGET#15]
Ios9 사용중인데 10부터 지원된다고 떠서 설치도 안되네요

**Comment by fimuxd** [comment]
네. 타겟 OS ver.를 10.0 으로 설정해놓았습니다. 
최초 v. 10.3 에서 수정하여 10.0 까지 내렸는데, 9 는 고려 대상에 없었네요..
iOS 9까지 지원하는 것은 아직 추후 업데이트 사항에 없습니다만 코드 리뷰 후 큰 문제가 없으면 업데이트에 반영하도록 하겠습니다. 고맙습니다.
