### ISSUE TITLE
Master Branch 기분만 Count가 되는것 같습니다. 

### ISSUE THREAD

**Issue by isjang98** [fimuxd/GITGET#16]
master branch 기준 commit 만 count 가 되는것 같네요

**Comment by fimuxd** [comment]
네 맞습니다.

현재 GitHub 자체의 Contributions Counting 규정에 따라서 Master (정확히 말하면 Default branch) 에 대한 Commit을 Contributions 로 인식하게 되어있습니다.

자세한 링크: https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

![screen shot 2017-12-05 at 02 23 24](https://user-images.githubusercontent.com/27915244/33566543-aa606e74-d963-11e7-874d-1bd525f517dd.png)

**Comment by blackturtle2** [comment]
이게 너무(?) 아쉬운 점인 것 같아요. 😞 
말 그대로 `Contributions`이니까요.ㅎㅎ
