### ISSUE TITLE
Today Contributions 

### ISSUE THREAD

**Issue by isjang98** [fimuxd/GITGET#28]
Today Contributions 이  날짜가 변하는 시점에서는 
Today Contributions  숫자 갱신이 제대로 안되짐 

 - Logout 후 Login하면은 정상동작

**Comment by fimuxd** [comment]
@isjang98 
이슈 남겨주셨는데 오늘에서야 봤네요.. 😅

해당 문제에 대해서는, 결론부터 말씀드리자면 일찍이 인지는 하고 있었지만 아직 어떻게 처리해야하는지 방법을 찾지 못하고 있는... 그런 상황입니다.

원인은 날짜가 변하는 현지시각 기준 시점과, Xcode - GitHub API 통신시 주고 받는? 기준 시점의 차이 때문인데요.
예를 들어서 Mac의 Safari 등으로 GitHub에 접속하면 한국시간으로 자정이 딱 지나면 다음날 `Contributions`가 뜹니다.(당연하죠...ㅎㅎ) 이유는 Mac이 현재 시간을 한국기준시로 인식을 하고 GitHub과 통신을 하니까 가능한 것으로 보여요.
그런데 똑같은 시간에 Xcode를 통해 접속하면 `Contributions`가 뜨지 않아요. 기준시가 UTC라 한국시간으로는 오전 9시가 되어야 정상적인 갱신이 되는거죠.

그렇다면 또 한가지 이해가 되지 않는 점이 생기는게 Logout 후 Login 하면 또 왜? 한국시각으로 통신하듯이 잘 동작하느냐? 하는거죠. (추측으로는 아마 새로고침을 하면 다시 0으로 돌아가지 않을까 싶기도 합니다..)

답변은 못 드리고 의문만 남기게 되었는데요. 전적으로 제가 Swift의 날짜 관련 객체들을 숙지하지 못한 이유가 큽니다.😭
조금 더 파보겠습니다. 이슈 남겨주셔서 감사합니다.
