### ISSUE TITLE
Today Extention 

### ISSUE THREAD

**Issue by isjang98** [fimuxd/GITGET#39]
GITHUB CONTRIBUTIONS 마킹이 적정하게 안됨. 
Month 가 나왔으면 좋겠습니다.

**Comment by fimuxd** [comment]
세상에... 이걸 한달이 넘어서야 확인했네요.
해당 문제는 해가 넘어가면서 (2017 -> 2018) 발생한 함수 오류였습니다.
지금은 해결된 상태입니다.
