### ISSUE TITLE
[request] 위젯 이름에도 "GITGET"이라고 표시되었으면 좋겠어요.

### ISSUE THREAD

**Issue by blackturtle2** [fimuxd/GITGET#4]
~옥의 티?~

지금은 `GITHUB CONTRIBUTIONS`로 표시되는데, 통일 되었으면 좋겠어요!

~이슈 클로즈는 편하실 때, 하시면 됩니당.ㅋㅋ 블로그에 댓글다는 느낌적인 느낌~

**Comment by fimuxd** [comment]
까북님 이제야 봤네요ㅋㅋ 
일부러 써드파티앱 느낌 안나게 하려고 그렇게 설정한 것인데.. 앱 이름이 더 낫나요? ㅎㅎ

**Comment by blackturtle2** [comment]
ㅋㅋ ~언제 보시려나 했~
제 생각에는 조금이라도 사용자에게 앱 이름을 기억하게 하고 싶어서요.
앱에서 위젯이 2개 이상 ~(어? 이거 가능한가..?)~ 이 아닌 다음에는 앱 이름으로 해야 한번이라도 더 사용자에게 각인이 될 것 같아요. 😆

**Comment by fimuxdtest** [comment]
다음 업데이트에 반영하겠습니다!
아마도 `GITGET - GITHUB CONTRIBUTIONS`  이 정도?

**Comment by fimuxd** [comment]
다음 업데이트에 반영하겠습니다!
아마도 GITGET - GITHUB CONTRIBUTIONS 이 정도?
