### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by soneji** [fimuxd/GITGET#53]
Hi

The app is no longer working. It is showing a black grid and not the proper contributions

Is there any reason why? Or anything I can do to help debug 

Thanks
Dhaval

**Comment by soneji** [comment]
hi @fimuxd why did you close this with no response? :(

**Comment by fimuxd** [comment]
My reply is too late. Sorry for closing the issue suddenly.
Over the past week, GITGET has been fully updated and version 2 is ready.
Width iOS14 target, I modified to use widgets on the Home Screen and reduced in-app functions a lot.
GITGET is currently on review the App Store, so you will be able to update it soon.
Thank you so much for your advice (especially for trying to help debug).
Happy new year 🎉 @soneji

**Comment by soneji** [comment]
Wow I'm super excited, thank you! Happy new year! <3
