### ISSUE TITLE
앱스토어 접근이 안됩니다.

### ISSUE THREAD

**Issue by evan-hwang** [fimuxd/GITGET#60]
![image](https://user-images.githubusercontent.com/10377550/113728236-df915480-9730-11eb-9815-8f155e3b3dad.png)
국가 지역 대한민국인데 접근이 안되네요 ㅠ

**Comment by Skyline-23** [comment]
저도 마찬가지로 국가제한걸리네요 ㅠㅠ

**Comment by fimuxd** [comment]
어떤 경로로 시도하셨는지 알 수 있을까요?
