### ISSUE TITLE
Mac OS 앱에서 유저를 찾을 수 없습니다

### ISSUE THREAD

**Issue by Skyline-23** [fimuxd/GITGET#62]
Mac OS의 위젯이 제 계정을 찾을 수 없다라고 뜹니다.
아직 정확하진 않지만 테스트를 해본 결과 Mac OS 위젯의 username에 숫자가 들어가게 된다면, 유저를 찾을 수 없는 것 같습니다.

**Comment by jjangga0214** [comment]
동일 증상입니다. 저도 숫자가 들어갑니다.

**Comment by sweetgoomba** [comment]
저는 숫자가 들어가지 않는데도 검색이 안되네요.

**Comment by fimuxd** [comment]
정말 오래 기다리셨습니다. 22.38.0 버전에서 버그 수정되었습니다.

**Comment by jjangga0214** [comment]
@fimuxd 수고 많으셨습니다 :)
