### ISSUE TITLE
Load error

### ISSUE THREAD

**Issue by HongChaeMin** [fimuxd/GITGET#63]
위젯에서 아이디 or 닉네임을 적어도 잔디가 안보여요…ㅠㅜ
아이디랑 닉네임이 같아야 보이는건가요?
아이디는 HongChaeMin이고 닉네임은 Hannah입니다😭

**Comment by fimuxd** [comment]
GitHub username을 입력하시면 됩니다. 
내 프로필 주소에서 github.com/`username` 으로 표시되는 부분입니다.
제대로 입력했음에도 invalid user라고 표현되던 버그는 22.38.0 버전에서 버그 수정되었습니다.
