### ISSUE TITLE
Invalid username

### ISSUE THREAD

**Issue by yubinjodev** [fimuxd/GITGET#68]
I entered my GitHub username and it says invalid username.. ![image](https://github.com/fimuxd/GITGET/assets/95195467/2345fe3e-263f-4834-9935-8f18886d351d)
![image](https://github.com/fimuxd/GITGET/assets/95195467/a2431deb-d50c-466f-831c-dade5ca8d1ab)

**Comment by minor-coder** [comment]
저도 맥북에서 똑같이 뜨네요 ㅠㅠ
MacOS Version: 17.0 App Version: 21.7.0
<img width="360" alt="스크린샷 2023-06-28 09 59 20" src="https://github.com/fimuxd/GITGET/assets/47618653/611eacdb-566b-4cfb-8e6f-f65e66811b43">

**Comment by roelvangils** [comment]
Same here.

**Comment by the-patience-tester** [comment]
I also get this issue I'm on macos version 14.0

**Comment by mattlovestech** [comment]
Same here

**Comment by yubinjodev** [comment]
![image](https://github.com/fimuxd/GITGET/assets/95195467/a141be24-de8e-40c4-84ef-267b9ee36c9f)

It's working fine now for me. Not sure what changed

**Comment by Tobils** [comment]
I have same issue, try multiple username and get invalid username. I've try on my ipad and iphone also got the same.
<img width="367" alt="Screenshot 2024-01-07 at 22 24 33" src="https://github.com/fimuxd/GITGET/assets/42987518/2db3e7d9-47f4-4ccf-9789-8d31650ae84d">

**Comment by Gloridust** [comment]
Same issue. I noticed that my username "Gloridust" is capitalized. I tried both 'Gloridust' and 'gloridust',but still not working.
@fimuxd

**Comment by ensup** [comment]
Same here

**Comment by anveloper** [comment]
same here

**Comment by gadhvirushiraj** [comment]
same here

**Comment by kimsijin33** [comment]
same here

**Comment by fimuxd** [comment]
Finally this issue is solved. Sorry guys. - New version 24.39.0

**Comment by ensup** [comment]
@fimuxd Thank you!
